#!/usr/bin/env bash
set -eo pipefail

# usage: . <target> [<flags>]
# - <target>: "home" or "work"
# - --skip-install: skips installing os/packages
# - --skip-dotfiles: skips installing dotfiles

target=${1:?}

source ./sync.log.sh

g_cond_install=true
if [[ "$@" =~ "--skip-install" ]]; then
	g_cond_install=false
fi

g_cond_dotfiles=true
if [[ "$@" =~ "--skip-dotfiles" ]]; then
	g_cond_dotfiles=false
fi

if [[ "$target" == "home" ]]; then
	source ./sync.target.home.sh
elif [[ "$target" == "work" ]]; then
	source ./sync.target.work.sh
else
	echo "error: args.target($target).invalid"
	exit 1
fi
