#!/usr/bin/env bash
set -eo pipefail

# usage: . <target> [<flags>]
# - <target>      "home" or "work"
# - --skip-install: skips installing os/packages
# - --skip-link:    skips linking dotfiles

target=${1:?}

source ./sync.log.sh

g_cond_install=true
if [[ "$@" =~ "--skip-install" ]]; then
	g_cond_install=false
fi

g_cond_link=true
if [[ "$@" =~ "--skip-link" ]]; then
	g_cond_link=false
fi

if [[ "$target" == "home" ]]; then
	source ./sync.target.home.sh
elif [[ "$target" == "work" ]]; then
	source ./sync.target.work.sh
else
	echo "error: args.target($target).invalid"
	exit 1
fi
