notARepository: quit

gui:
  mouseEvents: false
  showFileTree: false
  showRandomTip: false
  showBottomLine: false
  showBranchCommitHash: true
  commandLogSize: 1

customCommands:
  - key: <c-p>
    description: "Prune"
    context: localBranches
    command: git remote prune origin
    stream: true
    loadingText: Pruning...

  - key: <c-6>
    description: "Unhook"
    context: global
    command: rm -r ./.git/hooks
    stream: true
    loadingText: Unhooking...

  - key: <c-r>
    description: "Redate"
    context: commits
    command: git-redate {{.SelectedLocalCommit.Hash}} || true
    stream: true
    subprocess: true
    loadingText: Redating...
