notARepository: quit

gui:
  mouseEvents: false
  showRandomTip: false
  showBottomLine: false
  showBranchCommitHash: true
  commandLogSize: 1

customCommands:
  - key: 'p'
    context: 'global'
    command: 'git pull'
    subprocess: true
  - key: <c-p>
    description: "Prune"
    context: localBranches
    command: git remote prune origin
    stream: true
    loadingText: Pruning...

  - key: 'P'
    context: 'global'
    command: 'git push --force-with-lease'
    subprocess: true

