customCommands:
  - key: 'p'
    context: 'global'
    command: 'git pull'
    subprocess: true

  - key: 'P'
    context: 'global'
    command: 'git push --force-with-lease'
    subprocess: true

  - key: 'U'
    context: 'global'
    command: 'git remote prune origin'
    subprocess: true
