#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
userresources=$HOME/.Xresources
xmodmapconfig=$HOME/.xinitrc.xmodmap

if [ -f "$sysresources" ]; then xrdb -merge "$sysresources"; fi
if [ -f "$userresources" ]; then xrdb -merge "$userresources"; fi
if [ -f "$xmodmapconfig" ]; then source $xmodmapconfig; fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec awesome
