#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

script_dir=$(dirname -- "$(readlink -f -- "$0")")
dotfiles_dir=$script_dir/..
nixos_dir=$(readlink -f /etc/nixos)

source $script_dir/log.sh

log set install.nixos
if [[ ! $@ =~ "--no-install" ]]; then
	log task

	if [[ ! -h /etc/nixos ]]; then
		sudo rm -rf /etc/nixos
		sudo ln -sf $script_dir/_home_/nixos /etc/nixos
	fi

	if [[ $@ =~ "--update" ]]; then
		nix flake update $nixos_dir
	fi

	# [Flake not accessible through symlink](https://github.com/NixOS/nix/issues/8013)
	sudo nixos-rebuild switch --flake "$nixos_dir#default" --show-trace

	log done
else
	log skip
fi

log set dotfiles
if [[ ! $@ =~ "--no-dotfiles" ]]; then
	log task

	dotbot -c $dotfiles_dir/dotbot.yaml
	dotbot -c $dotfiles_dir/dotbot.home.yaml

	log done
else
	log skip
fi
