export EDITOR=nvim

if [[ $UNAME == "Linux" ]]; then
	export ZSH="/usr/share/oh-my-zsh-git"
	export UPDATE_ZSH_DAYS=7
	export ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
	[[ ! -d $ZSH_CACHE_DIR ]] && mkdir $ZSH_CACHE_DIR
elif [[ $UNAME == "Darwin" ]]; then
	export ZSH="$HOME/.oh-my-zsh"
	zstyle ':omz:update' mode auto
	zstyle ':omz:update' frequency 7
fi

# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="eastwood"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
	git
	fzf
	# fzf (https://github.com/junegunn/fzf)
	# CTRL-T (search files from pwd)
	# CTRL-R (search bash history)
	# ALT-C (search dirs, cd into them)
)

source $ZSH/oh-my-zsh.sh
export PATH="$HOME/.local/bin:$PATH"

bindkey -s "^a" "tmux a\n"
bindkey -s "^f" "$HOME/_dotfiles/tmux-sessioniser.sh\n"

alias cdx="cd ~/_dev"
alias cdz="cd ~/_zone"
alias cdd="cd ~/_dotfiles"

alias srczsh="source ~/.zshrc"
alias cfgzsh="(cd ~ && nvim .zshrc)"
alias cfggit="(cd ~ && nvim .gitconfig)"
alias cfgvim="(cd ~/.config/nvim && nvim .)"

alias ls="eza"
alias l="ls -l"
alias la="ls -la"

alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias lg="lazygit"

alias todo="nvim ~/_zone/todo.txt"

function deport() {
	port=$1
	filter=$2
	# get processes using port, discard first line of output
	matches="$(lsof -i:$port | tail -n +2)"
	# optionally filter process names with grep
	if [[ -n "$filter" ]]; then
		matches="$(echo $matches | grep $filter)"
	fi
	if [[ -z "$matches" ]]; then
		echo no matches
		return
	fi
	pids="$(echo $matches | awk '{print$2}')"
	echo $pids | xargs kill
	echo $matches
}

# == docker ==
# docker-destroy-containers
function ddc() {
	docker ps -aq | xargs docker rm -f
}

# docker-destroy-untagged-images
function ddui() {
	docker image ls | grep '<none>' | awk '{print $3}' | xargs docker rmi -f
}

function envload() {
	export $(grep -v '^#' $1 | xargs -0)
}

if [[ $UNAME == "Linux" ]]; then
	source ~/_dotfiles/zsh/zshrc.linux
elif [[ $UNAME == "Darwin" ]]; then
	source ~/_dotfiles/zsh/zshrc.macos
fi
