#!/usr/bin/env bash

export GIT_SERVE_DIR="$HOME/_/mirrors"

source $HOME/_/dotfiles/zsh/self.shared

# nodebox, node/npm/yarn/etc.
alias npm="nodebox npm"
alias npx="nodebox npx"
alias yarn="nodebox yarn"
